version: 1.0.{build}
configuration: Release
init:
- cmd: >-
    tzutil /s "Eastern Standard Time"

    choco install cake.portable --version 0.25.0 -r -y
before_build:
- cmd: cake
build:
  publish_nuget: true
  verbosity: minimal
cache:
  - packages