version: 1.0.{build}
configuration: Release
init:
- cmd: >-
    tzutil /s "Eastern Standard Time"

    choco install cake.portable -r -y
shallow_clone: true
before_build:
- cmd: cake
build:
  publish_nuget: true
  verbosity: minimal

